import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import { Providers } from "./provider";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body suppressHydrationWarning>
				<Providers>
					<div className="flex min-h-screen flex-col bg-gray-50">
						<Navbar />
						<main className="grow">{children}</main>
						<Footer />
					</div>
				</Providers>
			</body>
		</html>
	);
}
